<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <style>
        body {
            background-color: #f8f9fa;
        }

        .card {
            border: 1px solid #dee2e6;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .card-title {
            color: #007bff;
        }
    </style>
</head>
<body>
     

    <div class="container py-5">
    <a href="book.php" class="btn btn-danger" style="position: absolute; top: 50px; right: 60px; "> <i class="bi bi-house-gear-fill"></i></a>

        
       <!---- c'est la partie de traitement dynamique---->
       
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <h3 class="card-title mt-3">More details for: <?php echo $cls['marque'] . ' ' . $cls['model'] ?></h3>

                    <div class="card mt-4">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><strong>Couleur : </strong><?= $cls['couleur'] ?></li>
                            <li class="list-group-item"><strong>Puissance : </strong><?= $cls['puissance'] ?></li>
                            <li class="list-group-item"><strong>Nb_Place : </strong><?= $cls['nb_place'] ?></li>
                            <li class="list-group-item"><strong>Nb_Porte : </strong><?= $cls['nb_porte'] ?></li>
                            <li class="list-group-item"><strong>Poids : </strong><?= $cls['poids'] ?></li>
                            <li class="list-group-item"><strong>Cylindre: </strong><?= $cls['cylindre'] ?></li>
                            <li class="list-group-item"><strong>Prix : </strong><?= $cls['prix'] ?> DT </li>
                        </ul>
                        <div class="card-body">
                        <a href= "modifiercar.php?imatriculation= <?= $cls['imatriculation'] ?>" class="btn btn-success me-2"><i class="bi bi-pencil-square"></i> Edit</a>

                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
