<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <style>
        .container {
            position: relative;
        }

        .btn-danger {
            position: absolute;
            top: 50px;
            right: 60px;
        }
    </style>
</head>
<body>
    <div container py-4>
        <a href="book.php" class="btn btn-danger"> <i class="bi bi-house-gear-fill"></i></a>

        <!-- Dynamic processing part -->
        <div class="container text-center">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <h3 class="card-title mt-3 container py-5"> Modification</h3>
                    <form action="./modifiercar.php" method="POST">
                    <input type="text" class="form-control" value="<?= $_GET['imatriculation'] ?>" name="imatriculation" id="imatriculation	">

  <div class="mb-3">
    <label for="ex" class="form-label">Model</label>
    <input type="model" class="form-control" value="<?=$cls['model'] ?>" name="model" id="model" >
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Marque</label>
    <input type="marque" class="form-control" value="<?=$cls['marque'] ?>" name="marque" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Couleur</label>
    <input type="couleur" class="form-control" value="<?=$cls['couleur'] ?>" name="couleur" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Puissance</label>
    <input type="puissance" class="form-control" value="<?=$cls['puissance'] ?>" name="puissance" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Nb_Place</label>
    <input type="nbplace" class="form-control" value="<?=$cls['nb_place'] ?>" name="nb_place" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Nb_Porte</label>
    <input type="nbporte" class="form-control" value="<?=$cls['nb_porte'] ?>" name="nb_porte" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Poids</label>
    <input type="poids" class="form-control" value="<?=$cls['poids'] ?>" name="poids" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Cylindre</label>
    <input type="cylindre" class="form-control" value="<?=$cls['cylindre'] ?>" name="cylindre" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Prix</label>
    <input type="prix" class="form-control" value="<?=$cls['prix'] ?>" name="prix" id="exampleInputPassword1">
  </div>

  <button type="submit" class="btn btn-primary">Modifier</button>
  <button type="reset" class="btn btn-primary">Annuler</button>
  <br>
</form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
